services:

  registry-service:
    container_name: registry-service
    build:
      context: ./registry-service
    restart: unless-stopped
    ports:
      - "5112:5112"
    networks:
      vpcjava:
        ipv4_address: 172.51.1.2

  config-server:
    container_name: config-server
    build:
      context: ./config-server
    restart: unless-stopped
    ports:
      - "5113:5113"
    depends_on:
      - registry-service
    networks:
      vpcjava:
        ipv4_address: 172.51.1.3

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    restart: unless-stopped
    ports:
      - "5114:5114"
    depends_on:
      - config-server
    networks:
      vpcjava:
        ipv4_address: 172.51.1.4

  authentication-server:
    container_name: authentication-server
    build:
      context: ./authentication-server
    restart: unless-stopped
    ports:
      - "5115:5115"
    depends_on:
      - config-server
    networks:
      vpcjava:
        ipv4_address: 172.51.1.5

  resource-server:
    container_name: resource-server
    build:
      context: ./resource-server
    restart: unless-stopped
    ports:
      - "5116:5116"
    depends_on:
      - config-server
    networks:
      vpcjava:
        ipv4_address: 172.51.1.6

  saml2-server:
    container_name: saml2-server
    build:
      context: ./saml2-server
    restart: unless-stopped
    ports:
      - "5117:5117"
    depends_on:
      - config-server
    networks:
      vpcjava:
        ipv4_address: 172.51.1.7

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    restart: unless-stopped
    ports:
      - "5118:5118"
    depends_on:
      - config-server
    networks:
      vpcjava:
        ipv4_address: 172.51.1.8
        
  mysql57:
    container_name: mysql57
    image: mysql:5.7
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: java1234
      MYSQL_DATABASE: practice
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql/sql:/docker-entrypoint-initdb.d
    networks:
      vpcjava:
        ipv4_address: 172.51.1.11

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
    networks:
      vpcjava:
        ipv4_address: 172.51.1.12

  mongodb:
    container_name: mongodb
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: login
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongodb/data:/data/db
    networks:
      vpcjava:
        ipv4_address: 172.51.1.13

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      vpcjava:
        ipv4_address: 172.51.1.20

  nginx:
    container_name: web-server
    build:
      context: ./web-server
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      vpcjava:
        ipv4_address: 172.51.1.21

networks:
  vpcjava:
    driver: bridge
    ipam:
      config:
        - subnet: 172.51.0.0/16
          gateway: 172.51.0.1

volumes:
  db:
