services:

  nginx:
    container_name: web-server
    build:
      context: ./web-server
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - escola-network
          #ipv4_address: 172.51.1.1
  registry-service:
    container_name: registry-service
    build:
      context: ./registry-service
    restart: unless-stopped
    ports:
      - "5112:5112"
    networks:
      - escola-network
          #ipv4_address: 172.51.1.2
  config-server:
    container_name: config-server
    build:
      context: ./config-server
    restart: unless-stopped
    ports:
      - "5113:5113"
    depends_on:
      - registry-service
    networks:
      - escola-network
          #ipv4_address: 172.51.1.3
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    restart: unless-stopped
    ports:
      - "5114:5114"
    depends_on:
      - config-server
    networks:
      - escola-network
          #ipv4_address: 172.51.1.4
  authentication-server:
    container_name: authentication-server
    build:
      context: ./authentication-server
    restart: unless-stopped
    ports:
      - "5115:5115"
    depends_on:
      - config-server
    networks:
      - escola-network
          #ipv4_address: 172.51.1.5
  user-service:
    container_name: user-service
    build:
      context: ./user-service
    restart: unless-stopped
    ports:
      - "5116:5116"
    depends_on:
      - config-server
    networks:
      - escola-network
          #ipv4_address: 172.51.1.6
  saml2-server:
    container_name: saml2-server
    build:
      context: ./saml2-server
    restart: unless-stopped
    ports:
      - "5117:5117"
    depends_on:
      - config-server
    networks:
      - escola-network
          #ipv4_address: 172.51.1.7
  event-service:
    container_name: event-service
    build:
      context: ./event-service
    restart: unless-stopped
    ports:
      - "5118:5118"
    depends_on:
      - config-server
    networks:
      - escola-network
          #ipv4_address: 172.51.1.8

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - escola-network
      #ipv4_address: 172.52.2.11
networks:
  escola-network:
    external: true