server:
  servlet:
    context-path: /authentication-server
  port: 6114
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/registry-service/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: "TRACE"
spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/oauth2/**
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: saml2-server
          uri: lb://saml2-server
          predicates:
            - Path=/saml/**