server:
  port: 5113
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:5112/eureka/"
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/oauth2/**
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: saml2-server
          uri: lb://saml2-server
          predicates:
            - Path=/saml/**
        - id: resource-server
          uri: lb://resource-server
          predicates:
            - Path=/login/**