server:
  servlet:
    context-path: /registry-service
  port: ${REGISTRY_SERVICE_PORT}
spring:
  application:
    name: registry-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}:${REGISTRY_SERVICE_PORT}/registry-service/eureka
