server:
  servlet:
    context-path: /registry-service
  port: 6112
spring:
  application:
    name: registry-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/registry-service/eureka/
