server:
  port: 5112

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: 172.51.1.2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
