server:
  servlet:
    context-path: /registry-service
  port: 5112
spring:
  application:
    name: registry-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://registry-service:${server.port}/registry-service/eureka/
