services:

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: java1234
      MYSQL_DATABASE: practice
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - escola-network
          #ipv4_address: 172.52.2.2
  postgresdb:
    container_name: postgresdb
    image: postgres:15
    environment:
      POSTGRES_DB: practice
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - escola-network
          #ipv4_address: 172.52.2.3
  mongodb:
    container_name: mongodb
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: login
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - escola-network
          #ipv4_address: 172.52.2.4
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - escola-network
          #ipv4_address: 172.52.2.5
networks:
  escola-network:
    external: true

volumes:
  db: