server:
  servlet:
    context-path: /user-service
  port: 6116
spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: java1234
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:6115/authentication-server/oauth2/jwks
        opaque:
          introspection-uri: http://localhost:6115/authentication-server/oauth2/introspect
          introspection-client-id: clientCredentialsReference
          introspection-client-secret: c1BK9Bg2REeydBbvUoUeKCbD2bvJzXGj
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/registry-service/eureka/
management:
  endpoints:
    web:
      base-path: /user-service
      exposure:
        include: health
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: "TRACE"
resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 2s
  bulkhead:
    instances:
      paymentService:
        maxConcurrentCalls: 5
  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 2s