server:
  port: 6116
spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:login}"
    username: "${DATABASE_USERNAME:root}"
    password: "${DATABASE_PASSWORD:java1234}"
  jpa:
    show-sql: "true"
    hibernate:
      format_sql: "true"
      ddl-auto: "update"
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "${JWK_SET_URI:http://localhost:6115/oauth2/jwks}"
        opaque:
          introspection-uri: "${INTROSPECT_URI:http://localhost:6115/oauth2/introspect}"
          introspection-client-id: "${INTROSPECT_ID:clientCredentialsReference}"
          introspection-client-secret: "${INTROSPECT_SECRET:c1BK9Bg2REeydBbvUoUeKCbD2bvJzXGj}"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"

