server:
  port: 6115

spring:
  application:
    name: authentication-server
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: "mongodb://localhost:27017/login"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"