server:
  servlet:
    context-path: /config-server
  port: ${CONFIG_SERVER_PORT}
spring:
  profiles:
    active: native
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}/registry-service/eureka