server:
  servlet:
    context-path: /api-gateway
  port: ${API_GATEWAY_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}:${REGISTRY_SERVICE_PORT}/registry-service/eureka
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${AWS_ALB_DNS}:${ZIPKIN_PORT}/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  cloud:
    gateway:
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/oauth2/**
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: saml2-server
          uri: lb://saml2-server
          predicates:
            - Path=/saml/**