server:
  port: 5115
spring:
  data:
    mongodb:
      uri: "mongodb://mongouser:mongopass@mongodb:27017/login?authSource=admin"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}:${REGISTRY_SERVICE_PORT}/eureka
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${AWS_ALB_DNS}:${ZIPKIN_PORT}/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"