server:
  servlet:
    context-path: /authentication-server
  port: ${AUTHENTICATION_SERVER_PORT}
spring:
  data:
    mongodb:
      uri: "mongodb://mongouser:mongopass@mongodb.internal:27017/login?authSource=admin"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}/registry-service/eureka
management:
  endpoints:
    web:
      base-path: /authentication-server
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${AWS_ALB_DNS}:${ZIPKIN_PORT}/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE