server:
  port: 5115

spring:
  data:
    mongodb:
      uri: "mongodb://mongouser:mongopass@172.51.2.3:27017/login?authSource=admin"

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.51.1.2:5112/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://172.51.3.1:9411/api/v2/spans"

logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"