server:
  port: 5117
eureka:
  client:
    serviceUrl:
      defaultZone: ${AWS_ALB_DNS}:${REGISTRY_SERVICE_PORT}/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${AWS_ALB_DNS}:9411/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
spring:
  security:
    saml2:
      relyingparty:
        registration:
          carsonline:
            signing:
              credentials:
                - private-key-location: classpath:credentials/private.key
                  certificate-location: classpath:credentials/certificate.crt
            decryption:
              credentials:
                - private-key-location: classpath:credentials/private.key
                  certificate-location: classpath:credentials/certificate.crt
            assertingparty:
              metadata-uri: classpath:okta-metadata.xml