server:
  servlet:
    context-path: /saml2-server
  port: 5117
eureka:
  client:
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}/registry-service/eureka
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${AWS_ALB_DNS}:${ZIPKIN_PORT}/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  security:
    saml2:
      relyingparty:
        registration:
          carsonline:
            signing:
              credentials:
                - private-key-location: classpath:credentials/private.key
                  certificate-location: classpath:credentials/certificate.crt
            decryption:
              credentials:
                - private-key-location: classpath:credentials/private.key
                  certificate-location: classpath:credentials/certificate.crt
            assertingparty:
              metadata-uri: classpath:okta-metadata.xml