server:
  port: 5117

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.51.1.2:5112/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://172.51.1.20:9411/api/v2/spans"


spring:
  security:
    saml2:
      relyingparty:
        registration:
          carsonline:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            decryption:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            assertingparty:
              metadata-uri: "classpath:okta-metadata.xml"