server:
  servlet:
    context-path: /user-service
  port: 5116
spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    url: "jdbc:mysql://mysqldb:3306/login"
    username: "root"
    password: "java1234"
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "http://${AWS_ALB_DNS}/authentication-server/oauth2/jwks"
        opaque:
          introspection-uri: "http://${AWS_ALB_DNS}/authentication-server/oauth2/introspect"
          introspection-client-id: "clientCredentialsReference"
          introspection-client-secret: "c1BK9Bg2REeydBbvUoUeKCbD2bvJzXGj"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${AWS_ALB_DNS}/registry-service/eureka
management:
  endpoints:
    web:
      base-path: /user-service
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${AWS_ALB_DNS}:${ZIPKIN_PORT}/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE
resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 2s
  bulkhead:
    instances:
      paymentService:
        maxConcurrentCalls: 5
  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 2s