server:
  port: 5118

spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:172.51.1.11}:${DATABASE_PORT:3306}/${DATABASE_NAME:login}"
    username: "${DATABASE_USERNAME:root}"
    password: "${DATABASE_PASSWORD:java1234}"
  jpa:
    show-sql: "true"
    hibernate:
      format_sql: "true"
      ddl-auto: "update"

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.51.1.2:5112/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://172.51.1.20:9411/api/v2/spans"