server:
  servlet:
    context-path: /event-service
  port: 6118
spring:
  application:
    name: event-service
  cloud:
    config:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/registry-service/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: TRACE
azure:
  services:
    connections:
      topic:
        listener:
          connection:
          topic:
          subscriptionName:
        sender:
          connection:
          topic:
      queue:
        listener:
          connection:
          queue:
        sender:
          connection:
          queue: