name: AWS Deploy Microservices

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  dev-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Pre Terraform Init
        working-directory: ./aws-pre-terraform
        run: terraform init

      - name: Pre Terraform Validate
        working-directory: ./aws-pre-terraform
        run: terraform validate

      - name: Pre Terraform Plan
        working-directory: ./aws-pre-terraform
        run: terraform plan

      - name: Pre Terraform Apply
        working-directory: ./aws-pre-terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Get ALB URL from Terraform
        working-directory: ./aws-post-terraform
        id: alb
        run: |
          echo "ALB_URL=http://$(terraform output -raw alb_dns_url)" >> $GITHUB_ENV

      - name: Print ALB URL
        run: echo "ALB URL is $ALB_URL"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: ${{secrets.AWS_AUDIENCE}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build web-server Image
        working-directory: ./web-server
        env:
          WEB_SERVER_IMAGE_URI: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-1.amazonaws.com/${{secrets.AWS_WEB_SERVER_ECR_REPO}}:latest
        run: |
          docker build -t $WEB_SERVER_IMAGE_URI .
          docker push $WEB_SERVER_IMAGE_URI

      - name: Build registry-service Image
        working-directory: ./registry-service
        env:
          REGISTRY_SERVICE_IMAGE_URI: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-1.amazonaws.com/${{secrets.AWS_REGISTRY_SERVICE_ECR_REPO}}:latest
        run: |
          mvn clean install -DskipTests
          docker build -t $REGISTRY_SERVICE_IMAGE_URI .
          docker push $REGISTRY_SERVICE_IMAGE_URI

      - name: Build config-server Image
        working-directory: ./config-server
        env:
          CONFIG_SERVER_IMAGE_URI: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-1.amazonaws.com/${{secrets.AWS_CONFIG_SERVER_ECR_REPO}}:latest
          ALB_URL: ${{ env.ALB_URL }}

        run: |
          mvn clean install -DskipTests
          docker build -t $CONFIG_SERVER_IMAGE_URI .
          docker push $CONFIG_SERVER_IMAGE_URI

      - name: Build api-gateway Image
        working-directory: ./api-gateway
        env:
          API_GATEWAY_IMAGE_URI: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-1.amazonaws.com/${{secrets.AWS_API_GATEWAY_ECR_REPO}}:latest
        run: |
          mvn clean install -DskipTests
          docker build -t $API_GATEWAY_IMAGE_URI .
          docker push $API_GATEWAY_IMAGE_URI

      - name: Post Terraform Init
        working-directory: ./aws-post-terraform
        run: terraform init

      - name: Post Terraform Validate
        working-directory: ./aws-post-terraform
        run: terraform validate

      - name: Post Terraform Plan
        working-directory: ./aws-post-terraform
        run: terraform plan

      - name: Post Terraform Apply
        working-directory: ./aws-post-terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve