name: AWS Dev Deployment

on:
  push:
    branches: ["dev"]

permissions:
  id-token: write
  contents: read

jobs:
  dev-deploy:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    audience: ${{secrets.AWS_AUDIENCE}}
      #    role-to-assume: ${{secrets.AWS_ROLE_ARN}}
      #    aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Pre Terraform
        working-directory: ./aws-pre-terraform
        run: |
          terraform init -backend-config="bucket=dev-microservice-terraform-state"
          terraform validate -backend-config="bucket=dev-microservice-terraform-state"
          terraform plan -backend-config="bucket=dev-microservice-terraform-state"
          terraform apply -backend-config="bucket=dev-microservice-terraform-state" -auto-approve
          echo "AWS_ZIPKIN_ECR_REPO_URL=$(terraform output -raw zipkin_ecr_repository_url)" >> $GITHUB_ENV
          echo "AWS_WEB_SERVER_ECR_REPO_URL=$(terraform output -raw web_server_ecr_repository_url)" >> $GITHUB_ENV
          echo "AWS_REGISTRY_SERVICE_ECR_REPO_URL=$(terraform output -raw registry_service_ecr_repository_url)" >> $GITHUB_ENV
          echo "AWS_CONFIG_SERVER_ECR_REPO_URL=$(terraform output -raw config_server_ecr_repository_url)" >> $GITHUB_ENV
          echo "AWS_API_GATEWAY_ECR_REPO_URL=$(terraform output -raw api_gateway_ecr_repository_url)" >> $GITHUB_ENV
          echo "AWS_AUTHENTICATION_SERVER_ECR_REPO_URL=$(terraform output -raw authentication_server_ecr_repository_url)" >> $GITHUB_ENV

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build zipkin Image
        working-directory: ./other-service/zipkin
        env:
          ZIPKIN_IMAGE_URI: ${{env.AWS_ZIPKIN_ECR_REPO_URL}}:latest
        run: |
          docker build -t $ZIPKIN_IMAGE_URI .
          docker push $ZIPKIN_IMAGE_URI

      - name: Build web-server Image
        working-directory: ./web-server
        env:
          WEB_SERVER_IMAGE_URI: ${{env.AWS_WEB_SERVER_ECR_REPO_URL}}:latest
        run: |
          docker build -t $WEB_SERVER_IMAGE_URI .
          docker push $WEB_SERVER_IMAGE_URI

      - name: Build registry-service Image
        working-directory: ./registry-service
        env:
          REGISTRY_SERVICE_IMAGE_URI: ${{env.AWS_REGISTRY_SERVICE_ECR_REPO_URL}}:latest
        run: |
          mvn clean install -DskipTests
          docker build -t $REGISTRY_SERVICE_IMAGE_URI .
          docker push $REGISTRY_SERVICE_IMAGE_URI

      - name: Build config-server Image
        working-directory: ./config-server
        env:
          CONFIG_SERVER_IMAGE_URI: ${{env.AWS_CONFIG_SERVER_ECR_REPO_URL}}:latest
        run: |
          mvn clean install -DskipTests
          docker build -t $CONFIG_SERVER_IMAGE_URI .
          docker push $CONFIG_SERVER_IMAGE_URI

      - name: Build api-gateway Image
        working-directory: ./api-gateway
        env:
          API_GATEWAY_IMAGE_URI: ${{env.AWS_API_GATEWAY_ECR_REPO_URL}}:latest
        run: |
          mvn clean install -DskipTests
          docker build -t $API_GATEWAY_IMAGE_URI .
          docker push $API_GATEWAY_IMAGE_URI

      - name: Build authentication-server Image
        working-directory: ./authentication-server
        env:
          AUTHENTICATION_SERVER_IMAGE_URI: ${{env.AWS_AUTHENTICATION_SERVER_ECR_REPO_URL}}:latest
        run: |
          mvn clean install -DskipTests
          docker build -t $AUTHENTICATION_SERVER_IMAGE_URI .
          docker push $AUTHENTICATION_SERVER_IMAGE_URI

      - name: Post Terraform
        working-directory: ./aws-post-terraform
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve