name: Build & Deploy to EKS

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  dev-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: ${{secrets.AWS_AUDIENCE}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build web-server Image
        working-directory: ./web-server
        env:
          WEB_SERVER_IMAGE_URI: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-1.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}
        run: |
          docker build -t $WEB_SERVER_IMAGE_URI .
          docker push $WEB_SERVER_IMAGE_URI

      - name: Build api-gateway Image
        working-directory: ./api-gateway
        env:
          API_GATEWAY_IMAGE_URI: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.ap-south-1.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}
        run: |
          mvn clean install
          docker build -t $API_GATEWAY_IMAGE_URI .
          docker push $API_GATEWAY_IMAGE_URI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./aws-terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./aws-terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./aws-terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./aws-terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve